version: "3.6" 

services:
  graphql:
    image: graphql
    ports:
      - 4000:4000
    links:
      - "mongo:mongodb"
      
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

    
